# Dependencies
markdown:         kramdown
highlighter:         rouge

# Permalinks
permalink:        pretty

# Setup
title:            Just Write
tagline:          'Stop thinking about it and just do it'
description:      'Write Write Write Write, nothing complicated about it.'
url:              http://saifelokour.github.io

author:
  name:           'Saif Elokour'
  url:            https://twitter.com/tobeSaif

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/saifelokour

gems: [jekyll-paginate]